### ISSUE TITLE
Events To Add

### ISSUE THREAD

**Issue by Spartan322** [Arkhist/Hacknet-Pathfinder#44]
Post to further the list of necessary events to patch and add.

- [x] TerminalEvent (#46)
- [x] TerminalWriteEvent (#46) - canceling prevents writing to terminal
- [x] TerminalWriteAppendEvent (#46) - canceling prevents writing to terminal
- [x] TerminalWriteLineEvent (#46) - canceling prevents writing to terminal
- [ ] TerminalDrawEvent
