### ISSUE TITLE
TODO Comments in code

### ISSUE THREAD

**Issue by Fayti1703** [Arkhist/Hacknet-Pathfinder#45]
Tracking issue for any `TODO:` comments.

* "Error reporting":
    * [ ] [ContentLoader.cs, L137](https://github.com/Arkhist/Hacknet-Pathfinder/blob/5aecfeb4749b3e99a5d17cb787deaced7b6fcd86/Pathfinder/Internal/Replacements/ContentLoader.cs#L137), `MemoryDumpFile` executor, on `memoryInfo == null`
    * [ ] [SaveLoader.cs, L120](https://github.com/Arkhist/Hacknet-Pathfinder/blob/5aecfeb4749b3e99a5d17cb787deaced7b6fcd86/Pathfinder/Internal/Replacements/SaveLoader.cs#L120) `NetworkMap` executor, on `!Enum.TryParse<NetmapSortingAlgorithm>(...)`
    * [ ] [SaveLoader.cs, L233](https://github.com/Arkhist/Hacknet-Pathfinder/blob/5aecfeb4749b3e99a5d17cb787deaced7b6fcd86/Pathfinder/Internal/Replacements/SaveLoader.cs#L233) `LoadMission`, `catch` block for `ComputerLoader.readMission`
    * [ ] [SaveLoader.cs, L270](https://github.com/Arkhist/Hacknet-Pathfinder/blob/5aecfeb4749b3e99a5d17cb787deaced7b6fcd86/Pathfinder/Internal/Replacements/SaveLoader.cs#L270) `LoadMission`, on `endFuncData == null`
    * [ ] [SaveLoader.cs, L281](https://github.com/Arkhist/Hacknet-Pathfinder/blob/5aecfeb4749b3e99a5d17cb787deaced7b6fcd86/Pathfinder/Internal/Replacements/SaveLoader.cs#L281) `LoadMission`, on `postingData` == null
    * [ ] [SaveLoader.cs, L646](https://github.com/Arkhist/Hacknet-Pathfinder/blob/5aecfeb4749b3e99a5d17cb787deaced7b6fcd86/Pathfinder/Internal/Replacements/SaveLoader.cs#L646), `filesystem` executor, on `rootInfo == null`

* [ ] [PathfinderHooks.cs, L321](https://github.com/Arkhist/Hacknet-Pathfinder/blob/5aecfeb4749b3e99a5d17cb787deaced7b6fcd86/Pathfinder/PathfinderHooks.cs#L321): "Refactor that null out", `onLoadSaveFile` Hook, `OSLoadSaveFileEvent` construction.
