### ISSUE TITLE
Tracker for base game issues fixed in rewrite

### ISSUE THREAD

**Issue by Windows10CE** [Arkhist/Hacknet-Pathfinder#62]
Base game has some issues that can be fixed without affecting vanilla game/dlc/existing extensions.

- [x] DHS autoclears the remaining missions even if you tell it not to due to returning too early
- [x] SendEmail goal searches in the account folder instead of the inbox folder
- [x] DoesNotHaveFlags is missing from the lookup table for action types
- [x] SCInstantly doesn't null check current mission, leading to exceptions
- [x] SCOnConnect has faulty boolean logic for it's null check
- [x] HHBS (Striker hack) creates unused folders where it should use the extension save folder
